spring:
  application:
    name: client-service

  ## consul discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        heartbeat:
          enabled: true
        ## spring cloud is using ip-address
        hostname: localhost
    loadbalancer:
      ribbon:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/poc_client
    password: mysql
    username: root
  jpa:
    hibernate:
      ddl-auto: update

graphql:
  packages: com.turnkey.poc.client
  federation:
    enabled: true


server:
  port: 0
